#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
bindkey '^R' history-incremental-search-backward

export PATH=$PATH:$GOPATH/bin:/Users/jerodbury/bin

# added by travis gem
[ -f /Users/jerodbury/.travis/travis.sh ] && source /Users/jerodbury/.travis/travis.sh


